### ISSUE TITLE
$params['parentid'] always empty in SELECT

### ISSUE THREAD

**Issue by shortsteps** [zakkak/q2a-email-notifications-revised#8]
Hi all, 
I'm using this plugin in Q2A v. 1.7.4 on CentOS 7.3 with PHP v. 5.4.16 and MariaDB Server v. 5.5.52.
When submitting a new question, the browser shows a PHP error.
![schermata 2017-05-18 alle 14 42 04 2](https://user-images.githubusercontent.com/20532652/27694189-af23a6dc-5ceb-11e7-959a-3589964bc22c.png)
Question is correctly posted but emails are not sented.

In logs I have this error

> [Thu May 18 14:45:44.643284 2017] [:error] [pid 10763] [client 10.90.0.1:57748] PHP Question2Answer MySQL query error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')))) GROUP BY email' at line 1 - Query: SELECT email from qa_useremailsubscription as sub LEFT JOIN qa_userfavorites as fav ON (sub.userid = fav.userid) WHERE (favoritesonly = b'0') OR (favoritesonly = b'1' AND ((fav.entitytype = 'C' AND fav.entityid IN (0)) OR (fav.entitytype = 'Q' AND (fav.entityid = 8 OR fav.entityid = )))) GROUP BY email, referer: http://q2a.extrasys.it/index.php/ask

It looks like at the end of the SELECT the key fav.entityid has no value. Any ideas?
What does `fav.entityid = ".$params['parentid']."` (line 59 in qa-user-email-notifications-event.php) refers to? 

Thanks

**Comment by zakkak** [comment]
Hmm not sure I remember, but i think it is a way to check if you have the specific post on your favorites or its parent. I guess you need to add `'` around the value in order to work even when the `parentid` is not available/set.

**Comment by shortsteps** [comment]
Great, it solved for me. Sorry for the dummy issue but I'm not expert with such syntax.
I guess it is never set in my case because we don't use favorites at all. In our env Moderators, Editors, etc who subscribed receive emails thanks to their role with no need to favorite an item or person.

Thanks a lot!
